### PR TITLE
Multi cartesian product fix

### LINKED ISSUE #73: Replace multi_cartesian_product with a correct version
We currently use itertools::multi_cartesian_product in many places. Unfortunately it doesn't handle empty iterators correctly (it produces no results when it should produce a single empty result); see https://github.com/rust-itertools/itertools/issues/337. In several places we handle this ourselves but it would be better to just use a correct version everywhere.

We can implement the correct version by wrapping itertools::multi_cartesian_product.

### PR DESCRIPTION
**Pull request by wilcoxjay**
This PR implements a corrected wrapper around `itertools::multi_cartesian_product`.

I added a CI lint that forbids the string `multi_cartesian_product` (as a standalone word, not a substring, as decided by `grep -w`) from the code base. Use the wrapper `multi_cartesian_product_fixed` instead.

I ported all existing call sites to use the fixed version. I considered each call site manually and convinced myself that either the iterator was never empty or that the old code did not correctly handle that case already. I also removed some obvious workarounds that handled the empty iterator case separately to avoid the bug.

Fixes #73

### CODE REVIEW

File: tools/ci-check.sh [hunk 1]
```diff
@@ -113,3 +113,10 @@ else
   cargo doc --quiet --document-private-items --no-deps
 fi
 end_group
+
+start_group "project-specific lints"
+if grep -wr --include '*.rs' --exclude ouritertools.rs multi_cartesian_product; then
+  error "found some occurrences of multi_cartesian_product"
```
Comment (tchajed) [inline tools/ci-check.sh:119]:
```suggestion
  error "found some occurrences of multi_cartesian_product; use multi_cartesian_product_fixed to handle empty iterators correctly"
```

**Review by tchajed — COMMENTED** [review]
Looks great to me! I wish the underlying bug were fixed but in the mean time this is a solid solution, and you even added a lint for it.
